// AprendiendoReact/src/components/Home.tsx
import Slider from "./Slider"
import Siderbar from "./Sidebar"
import Articles from "./Articles"

export default function Home() {
    return (
        <div id="home">
            <Slider
                title="Aprendiendo React"
                btn="Ir al blog"
                size="slider-big"
            />
            <div className="center">
                <div className="center">
                    <h1>Ultimos Articulos</h1>
                    <Articles home='true' />
                </div>
                <Siderbar></Siderbar>
            </div>

        </div >
    )
}

// AprendiendoAngular/src/app/components/home/home.component.ts
import { Component } from '@angular/core';
import { SidebarComponent } from '../sidebar/sidebar.component';
import { SliderComponent } from '../slider/slider.component';

@Component({
  selector: 'app-home',
  standalone: true,
  imports: [SidebarComponent, SliderComponent],
  templateUrl: './home.component.html',
  styleUrl: './home.component.css'
})
export class HomeComponent {
  title = 'Ultimos articulos'
}

<app-slider nombre='Aprendiendo Angular'></app-slider>

<div class="center">
  <section id="content">
    <h2 class="subheader">{{ title }}</h2>
  </section>

  <app-sidebar></app-sidebar>
</div>
