// AprendiendoAngular/src/app/components/article/article.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { SliderComponent } from '../slider/slider.component';
import { SidebarComponent } from '../sidebar/sidebar.component';
import { ArticleService } from '../../services/article.service';
import { Article } from '../../models/article';
import { ActivatedRoute, Router } from '@angular/router';
import { MomentModule } from 'ngx-moment';
import { Global } from '../../services/global';


@Component({
  selector: 'app-article',
  standalone: true,
  imports: [SliderComponent, SidebarComponent, MomentModule],
  templateUrl: './article.component.html',
  styleUrl: './article.component.css'
})
export class ArticleComponent implements OnInit {

  public article?: Article

  url: string = Global.url

  _articleService = inject(ArticleService)
  _route = inject(ActivatedRoute)
  _router = inject(Router)

  ngOnInit() {
    this._route.params.subscribe(
      (params) => {
        const id = params['id'];
  
        this._articleService.getArticle(id).subscribe(
          {
            next: (response) => (this.article = response.article),
            error: (error) => {
              console.error(error);
              this._router.navigate(['/home']); // Handle error and redirect
            },
          }
        );
      }
    );
  }
  

}

<div class="center">
  @if (article) {

  <section id="content">
    <h1 class="subheader">Nombre articulo</h1>
    <article class="article-item article-detail">
      <div class="image-wrap">
        @if (article.image) {
        <img
          src="{{ url + '' + 'get-img/' + article.image }}"
          alt="{{ article.title }}"
        />
        } @else {
        <img src="#" alt="#" />
        }
      </div>

      <h1 class="subheader">{{ article.title }}</h1>
      <span class="date">
        {{ article.date | amLocale : "es" | amTimeAgo }}
      </span>
      <p>
        {{ article.content }}
      </p>

      <div class="buttons">
        <a href="#" class="btn btn-warning">Editar</a>
        <a href="#" class="btn btn-danger">Borrar</a>
      </div>

      <div class="clearfix"></div>
    </article>
  </section>
  }
</div>

<app-sidebar></app-sidebar>

// AprendiendoReact/src/components/Article.tsx
import axios from "axios";
import { Global } from "../Global";
import { Link, useNavigate, useParams } from "react-router-dom";
import Sidebar from "./Sidebar";
import { useEffect, useState } from "react";
import { ApiArticleResponse } from "../Interfaces";

export default function Article() {
    const navigate = useNavigate();
    const params = useParams()
    const url = Global.url + 'article/' + params.id

    const [loading, setLoading] = useState(true);
    const [article, setArticle] = useState<ApiArticleResponse>({ status: '', article: {} })

    const deleteArticle = async () => {
        try {
            await axios.delete(url);
            // Redirigir después de eliminar el artículo
            navigate('/blog');
        } catch (error) {
            console.error("Error deleting article", error);
        }
    };

    useEffect(() => {
        axios.get<ApiArticleResponse>(url)
            .then((res) => {
                setArticle(res.data);
                console.log(article)
                setLoading(false); // Cambiar el estado de carga cuando se carguen los datos
            })
            .catch(error => {
                console.error(error);
                setLoading(false); // Cambiar el estado de carga en caso de error
            });
    }, []);

    const renderArticle = () => {
        const { title, content, image, date } = article.article
        return (
            < article className="article-item article-detail" >
                <div className="image-wrap">
                    <img src={image} alt="Paisaje" />
                </div>

                <h1 className="subheader">{title}</h1>
                <span className="date">
                    {date}
                </span>
                <p>
                    {content}
                </p>
                <button onClick={() => {
                    deleteArticle()
                }} className="btn btn-warning">Editar</button>
                <button onClick={() => {
                    deleteArticle()
                }} className="btn btn-danger">Eliminar</button>

                <div className="clearfix"></div>
            </article >

        )
    }


    return (
        <div className="center">
            <section id="content">
                {loading ? (
                    <p>Cargando...</p>
                ) : (
                    renderArticle()
                )

                }


            </section>

            <Sidebar></Sidebar>
        </div>

    )
}
