// AprendiendoAngular/src/app/components/sidebar/sidebar.component.ts
import { Component, inject } from '@angular/core';
import { FormControl, FormGroup, FormsModule, ReactiveFormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';

@Component({
  selector: 'app-sidebar',
  standalone: true,
  imports: [FormsModule, ReactiveFormsModule, RouterLink],
  templateUrl: './sidebar.component.html',
  styleUrl: './sidebar.component.css'
})
export class SidebarComponent {


  _router = inject(Router)
  _route = inject(ActivatedRoute)

  searchForm = new FormGroup({
    searchString: new FormControl('')
  })


  goSearch() {
    this._router.navigate(['/buscar', this.searchForm.get('searchString')?.value])
  }

}

<aside id="sidebar">
    <div id="nav-blog" class="sidebar-item">
        <h3>Puedes hacer esto</h3>
        <a href="#" class="btn btn-success">Crear artículo</a>
        <a routerLink="['blog/crear']"></a>
    </div>

    <div id="search" class="sidebar-item">
        <h3>Buscador</h3>
        <p>Encuentra el artículo que buscas</p>

            <form [formGroup]="searchForm" (submit)="goSearch()">
                <input type="text" name="search" formControlName="searchString"/>
                <input type="submit" name="submit" value="Buscar" class="btn"/>
            </form>

    </div>
</aside>

<div class="clearfix"></div>

// AprendiendoReact/src/components/Sidebar.tsx
import { FormEvent, useState } from "react";
import { Link, useNavigate } from "react-router-dom";

export default function Sidebar({ blog }: { blog?: string }) {

  const [searchRef, setSearchRef] = useState({
    search: '',
    redirect: false
  });
  const navigate = useNavigate();

  const handleInputChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    setSearchRef({
      ...searchRef,
      [e.target.name]: e.target.value
    });
  };

  const redirectToSearch = (e: FormEvent) => {
    e.preventDefault();
    navigate(`/blog/busqueda/${searchRef.search}`);
  };

  return (
    <aside id="sidebar">
      {blog === 'true' &&
        <div id="nav-blog" className="sidebar-item">
          <h3>Puedes hacer esto</h3>
          <Link to={'/blog/crear'} className="btn btn-success">
            Crear artículo
          </Link>
        </div>
      }

      <div id="search" className="sidebar-item">
        <h3>Buscador</h3>
        <p>Encuentra el artículo que buscas</p>
        <form onSubmit={redirectToSearch}>
          <input
            type="text"
            name="search"
            value={searchRef.search}
            onChange={handleInputChange}
          />
          <input type="submit" name="submit" value="Buscar" className="btn" />
        </form>
      </div>
    </aside>
  );
  
}
